### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by dennisarimi**
Screenshot 2024-01-02 at 11 34 48 PM

### CODE REVIEW

**Comment by dennisarimi** [comment]
will add state functionality to maintain active page being underlined in navbar, in next pr

**Comment by dennisarimi** [comment]
new look
Screenshot 2024-01-03 at 6 33 47 PM

**Review by MatthewOlaka — COMMENTED** [review]
Could we change the new files (i.e. icons, site_images, team_images) to not have the " 2" as part of the file name?

so "briefcase 2.svg" -----> "briefcase.svg" and so on...

**Comment by dennisarimi** [comment]
> Could we change the new files (i.e. icons, site_images, team_images) to not have the " 2" as part of the file name?
> 
> so "briefcase 2.svg" -----> "briefcase.svg" and so on...

Done 👍

**Comment by MatthewOlaka** [comment]
LGTM! but could you resolve the merge conflicts before i approve?

**Comment by dennisarimi** [comment]
> LGTM! but could you resolve the merge conflicts before i approve?

Done 🕺🏾

**Review by MatthewOlaka — APPROVED** [review]
🧶

**Pull request merged**
